name: notebook
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alembic=1.8.1=pyhd8ed1ab_0
  - alsa-lib=1.2.8=h166bdaf_0
  - anyio=3.6.1=pyhd8ed1ab_1
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py37h540881e_2
  - arpack=3.7.0=hdefa2d7_2
  - async_generator=1.10=py_0
  - atk-1.0=2.38.0=hd4edc92_1
  - attr=2.5.1=h166bdaf_1
  - attrs=22.1.0=pyh71513ae_1
  - babel=2.10.3=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - binutils=2.36.1=hdd6e379_2
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_10
  - bleach=5.0.1=pyhd8ed1ab_0
  - blinker=1.5=pyhd8ed1ab_0
  - brotlipy=0.7.0=py37h540881e_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-compiler=1.6.0=hd590300_0
  - ca-certificates=2022.9.24=ha878542_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2022.9.24=pyhd8ed1ab_0
  - certipy=0.1.3=py_0
  - cffi=1.15.1=py37h43b0acd_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - chrpath=0.16=h7f98852_1002
  - compilers=1.6.0=ha770c72_0
  - cryptography=38.0.2=py37h5994e8b_1
  - curl=8.1.2=h409715c_0
  - cxx-compiler=1.6.0=h00ab1b0_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.3=py37hd23a5d3_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - elfutils=0.189=hde5d1a3_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - fftw=3.3.10=nompi_hc118613_108
  - flit-core=3.7.1=pyhd8ed1ab_0
  - fltk=1.3.8=h83e168f_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fortran-compiler=1.6.0=heb67821_0
  - freetype=2.12.1=hca18f0e_1
  - fribidi=1.0.10=h36c2ea0_0
  - gcc=12.1.0=h9ea6d83_10
  - gcc_impl_linux-64=12.1.0=hea43390_17
  - gcc_linux-64=12.1.0=h3bb4806_10
  - gdk-pixbuf=2.42.10=h05c8ddd_0
  - gettext=0.21.1=h27087fc_0
  - gfortran=12.1.0=h6fcb4f1_10
  - gfortran_impl_linux-64=12.1.0=h1db8e46_17
  - gfortran_linux-64=12.1.0=h7ec3724_10
  - ghostscript=9.54.0=h27087fc_2
  - giflib=5.2.1=h0b41bf4_3
  - gl2ps=1.4.2=h0708190_0
  - glad=0.1.36=h0b41bf4_1
  - glfw=3.3.8=hd590300_1
  - glib=2.76.4=hfc55251_0
  - glib-tools=2.76.4=hfc55251_0
  - glpk=5.0=h445213a_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py37h025e8b9_0
  - gnuplot=5.4.5=h142138f_1
  - gnutls=3.7.8=hf3e180e_0
  - graphicsmagick=1.3.40=hcb5e50b_0
  - graphite2=1.3.13=h58526e2_1001
  - greenlet=1.1.3=py37hd23a5d3_0
  - gst-plugins-base=1.22.0=h4243ec0_2
  - gstreamer=1.22.0=h25f0c4b_2
  - gstreamer-orc=0.4.34=hd590300_0
  - gtk2=2.24.33=h90689f9_2
  - gxx=12.1.0=h9ea6d83_10
  - gxx_impl_linux-64=12.1.0=hea43390_17
  - gxx_linux-64=12.1.0=h1f501c1_10
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf5=1.12.2=nompi_h4df4325_101
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py37h89c1867_0
  - importlib_resources=5.10.0=pyhd8ed1ab_0
  - ipykernel=6.16.0=pyh210e3f2_0
  - ipython=7.33.0=py37h89c1867_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.2=pyhd8ed1ab_1
  - jack=1.9.22=h11f4161_0
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h0b41bf4_3
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.16.0=pyhd8ed1ab_0
  - jupyter-offlinenotebook=0.2.2=pyh1d7be83_0
  - jupyter-resource-usage=0.6.3=pyhd8ed1ab_0
  - jupyter_client=7.4.2=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py37h89c1867_0
  - jupyter_server=1.21.0=pyhd8ed1ab_0
  - jupyter_telemetry=0.1.0=pyhd8ed1ab_1
  - jupyterhub-base=1.5.0=py37h89c1867_1
  - jupyterhub-singleuser=1.5.0=py37h89c1867_1
  - jupyterlab=3.4.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.15.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.3=pyhd8ed1ab_0
  - kernel-headers_linux-64=2.6.32=he073ed8_16
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libaec=1.0.6=hcb278e6_1
  - libarchive=3.6.2=h3d51595_0
  - libblas=3.9.0=17_linux64_openblas
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=17_linux64_openblas
  - libclang=15.0.7=default_h7634d5b_3
  - libclang13=15.0.7=default_h9986a30_3
  - libcups=2.3.3=h36d4200_3
  - libcurl=8.1.2=h409715c_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.17=h0b41bf4_0
  - libdrm=2.4.114=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h28343ad_4
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-devel_linux-64=12.1.0=h1ec3361_17
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgcrypt=1.10.1=h166bdaf_0
  - libgd=2.3.3=h5aea950_4
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libglib=2.76.4=hebfc3b9_0
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=12.1.0=h8d9b700_16
  - libgpg-error=1.47=h71f35ed_0
  - libhwloc=2.9.1=hd6dc26d_0
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h166bdaf_0
  - liblapack=3.9.0=17_linux64_openblas
  - liblapacke=3.9.0=17_linux64_openblas
  - libllvm15=15.0.7=hadd5161_1
  - libllvm16=16.0.1=hadd5161_0
  - libmicrohttpd=0.9.77=h97afed2_0
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.17=h166bdaf_0
  - libpng=1.6.39=h753d276_0
  - libpq=15.3=hbcd7760_1
  - libsanitizer=12.1.0=ha89aaad_17
  - libsndfile=1.2.0=hb75c966_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=12.1.0=h1ec3361_17
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libsystemd0=253=h8c4010b_1
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.5.0=h6adf6a1_2
  - libtool=2.4.7=h27087fc_0
  - libudev1=253=h0b41bf4_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.44.2=h166bdaf_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - make=4.3=hd18ef5c_1
  - mako=1.2.3=pyhd8ed1ab_0
  - markupsafe=2.1.1=py37h540881e_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mesalib=23.0.2=h3855f93_0
  - metis=5.1.1=h59595ed_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.0=hb012696_0
  - mpg123=1.31.3=hcb278e6_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - mysql-common=8.0.33=hf1915f5_2
  - mysql-libs=8.0.33=hca2cd23_2
  - nbclassic=0.4.6=pyhd8ed1ab_0
  - nbclient=0.7.0=pyhd8ed1ab_0
  - nbconvert=7.2.1=pyhd8ed1ab_0
  - nbconvert-core=7.2.1=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.1=pyhd8ed1ab_0
  - nbformat=5.7.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.8.1=hc379101_1
  - nodejs=18.15.0=h8d033a5_0
  - notebook=6.4.12=pyha770c72_0
  - notebook-shim=0.1.0=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - nteract_on_jupyter=2.1.3=py_0
  - oauthlib=3.2.1=pyhd8ed1ab_0
  - octave=7.3.0=h4bc5dab_3
  - openssl=3.1.1=hd590300_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=21.3=pyhd8ed1ab_0
  - pamela=1.0.0=py_0
  - pandoc=2.19.2=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.14=hd33c08f_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.40=hc3806b6_0
  - perl=5.32.1=4_hd590300_perl5
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=22.2.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - plotly=5.15.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - portaudio=19.6.0=h583fa2b_7
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.31=pyha770c72_0
  - psutil=5.9.2=py37h540881e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=16.1=hcb278e6_3
  - pulseaudio-client=16.1=h5195f5e_3
  - pulseaudio-daemon=16.1=ha8d29e2_3
  - pycparser=2.21=pyhd8ed1ab_0
  - pycurl=7.45.1=py37he47804d_2
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyjwt=2.5.0=pyhd8ed1ab_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py37hf30b843_1
  - pyqt5-sip=12.11.0=py37hd23a5d3_1
  - pyrsistent=0.18.1=py37h540881e_1
  - pysocks=1.7.1=py37h89c1867_5
  - python=3.7.12=hf930737_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-json-logger=2.0.1=pyh9f0ad1d_0
  - python_abi=3.7=2_cp37m
  - pytz=2022.4=pyhd8ed1ab_0
  - pyzmq=24.0.1=py37h0c0c2a8_0
  - qhull=2020.2=h4bd325d_2
  - qscintilla2=2.13.3=py37hf30b843_3
  - qt-main=5.15.8=h5d23da1_6
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_1
  - ruamel.yaml=0.17.21=py37h540881e_1
  - ruamel.yaml.clib=0.2.6=py37h540881e_1
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.4.1=pyhd8ed1ab_0
  - sip=6.7.2=py37hd23a5d3_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlalchemy=1.4.41=py37h540881e_0
  - sqlite=3.40.0=h4ff8645_0
  - suitesparse=5.10.1=h9e50725_1
  - sundials=6.5.1=h777d08e_3
  - sympy=1.10.1=py37h89c1867_1
  - sysroot_linux-64=2.12=he073ed8_16
  - tbb=2021.9.0=hf52228f_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - terminado=0.16.0=pyh41d4057_0
  - texinfo=7.0=pl5321h0f457ee_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.2=py37h540881e_0
  - traitlets=5.4.0=pyhd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.1=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=4.0.3=pyhd8ed1ab_0
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xeus=3.0.5=hac2b420_1
  - xeus-octave=0.1.0=he98adf6_5
  - xeus-zmq=1.0.2=h0541b36_2
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-damageproto=1.2.1=h7f98852_1002
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-glproto=1.4.17=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxcursor=1.2.0=h0b41bf4_1
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxinerama=1.1.5=h27087fc_0
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.3.0=hd590300_0
  - xorg-randrproto=1.5.0=h7f98852_1001
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-util-macros=1.19.3=h7f98852_0
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.9.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.2=hfc55251_7
