name: xeus-octave
channels:
  - conda-forge
dependencies:
  - xeus-octave ==0.2.0
  # For Plotly graphical toolkit
  - plotly
  # Runtime dependency for Octave ``symbolic`` package.
  - sympy
  # For compiling the Octave ``control`` and ``signal`` packages
  - compilers
  - make
  # for annotate jupyter cells (not in rise mode, but persists)
  - jupyter-annotation-tool-ipynbd
  # for jupyter lab rise (works with XOctave, and XOctave only works jupyterlab)
  - jupyterlab_rise
  # for jupyter notebook rise (disable because only works for octave, but octave hard to make graphs
  #- rise
  #- pip:
  #   - jupyter-contrib-nbextensions