name: xeus-octave
channels:
  - conda-forge
dependencies:
  - xeus-octave ==0.2.0
  # For Plotly graphical toolkit
  - plotly
  # Runtime dependency for Octave ``symbolic`` package.
  - sympy
  # For compiling the Octave ``control`` and ``signal`` packages
  - compilers
  - make
  # for annotate jupyter cells (not in rise mode, but persists)
  - jupyter-annotation-tool-ipynb
  # for jupyter lab rise
  - jupyterlab_rise
  # for jupyter notebook rise
  - rise
  - pip:
     - jupyter-contrib-nbextensions